name: genefamilyflow
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - hmmer
  - blast
  - muscle
  - iqtree
  - meme
  - seqkit
  - clustalw
  - jcvi
  - pandas
  - pyyaml
  - biopython
  - click
  - r-base
  - r-tidyverse
  - r-readxl
  - r-writexl
  - r-pheatmap
  - r-patchwork
  - r-circlize
  - r-complexheatmap
  - r-data.table
  - bioconductor-biostrings
  - bioconductor-treeio
  - bioconductor-clusterprofiler
  - pip:
      - gffutils
