"""Tests for scripts/scan_promoter_fimo.py.

Mocks FIMO output so the tests run in CI without the MEME suite. The
end-to-end ``scan()`` path that actually invokes FIMO is exercised in a
separate guarded test (skipped when the binary is missing).
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from scripts.scan_promoter_fimo import (
    FIMO_COLUMNS,
    FimoHit,
    SPECIES_TAG,
    parse_fimo_tsv,
    run_fimo,
    scan,
    write_plantcare_tab,
)

pytestmark = pytest.mark.unit


def _row(**overrides: str) -> str:
    base = {
        "motif_id": "MA0021.1",
        "motif_alt_id": "Dof3",
        "sequence_name": "Sobic.001G032000.v3.1",
        "start": "10",
        "stop": "17",
        "strand": "+",
        "score": "12.5",
        "p-value": "1e-5",
        "q-value": "1e-3",
        "matched_sequence": "ACGTACGT",
    }
    base.update(overrides)
    return "\t".join(base[col] for col in FIMO_COLUMNS) + "\n"


def _write_fimo_tsv(path: Path, rows: list[str]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = "\t".join(FIMO_COLUMNS) + "\n"
    body = header + "".join(rows) + "\n# CISML XML reference: fimo.cisml.xml\n"
    path.write_text(body)
    return path


class TestParseFimoTsv:
    def test_basic_row(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(tmp_path / "fimo.tsv", [_row()])
        hits = list(parse_fimo_tsv(tsv))
        assert len(hits) == 1
        h = hits[0]
        assert h.raw_id == "Sobic.001G032000.v3.1"
        assert h.element == "Dof3"
        assert h.sequence == "ACGTACGT"
        assert h.position == 10
        assert h.length == 8  # 17 - 10 + 1
        assert h.strand == "+"
        assert h.species == SPECIES_TAG
        assert h.function_desc == "MA0021.1"

    def test_empty_alt_id_falls_back_to_motif_id(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(
            tmp_path / "fimo.tsv",
            [_row(motif_alt_id="", motif_id="MA0042.2")],
        )
        hits = list(parse_fimo_tsv(tsv))
        assert hits[0].element == "MA0042.2"
        assert hits[0].function_desc == "MA0042.2"

    def test_strand_normalization(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(
            tmp_path / "fimo.tsv",
            [_row(strand="-"), _row(strand="+")],
        )
        strands = sorted(h.strand for h in parse_fimo_tsv(tsv))
        assert strands == ["+", "-"]

    def test_skips_blank_and_comment_lines(self, tmp_path: Path) -> None:
        path = tmp_path / "fimo.tsv"
        path.write_text(
            "\t".join(FIMO_COLUMNS) + "\n"
            "\n"
            "# generated by FIMO\n"
            + _row()
            + "\n"
            "# trailing comment\n"
        )
        assert len(list(parse_fimo_tsv(path))) == 1

    def test_drops_truncated_row(self, tmp_path: Path) -> None:
        path = tmp_path / "fimo.tsv"
        path.write_text(
            "\t".join(FIMO_COLUMNS) + "\n"
            + "MA0021.1\tDof3\tg1\n"  # too few columns
            + _row()
        )
        hits = list(parse_fimo_tsv(path))
        assert len(hits) == 1

    def test_drops_non_int_coords(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(
            tmp_path / "fimo.tsv",
            [_row(start="oops"), _row()],
        )
        hits = list(parse_fimo_tsv(tsv))
        assert len(hits) == 1

    def test_normalizes_strand_suffix_in_sequence_name(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(
            tmp_path / "fimo.tsv",
            [_row(sequence_name="Sobic.001G032000.v3.1(+)")],
        )
        hits = list(parse_fimo_tsv(tsv))
        # Reused _normalize_raw_id strips the strand suffix so R parses it
        assert hits[0].raw_id == "Sobic.001G032000.v3.1"


class TestWritePlantcareTab:
    def test_8_column_format(self, tmp_path: Path) -> None:
        hits = [
            FimoHit(
                raw_id="Sobic.001G032000.v3.1",
                element="Dof3",
                sequence="ACGTACGT",
                position=10,
                length=8,
                strand="+",
                species=SPECIES_TAG,
                function_desc="MA0021.1",
            ),
            FimoHit(
                raw_id="Sobic.001G032100.v3.1",
                element="MYB",
                sequence="CACGTG",
                position=42,
                length=6,
                strand="-",
                species=SPECIES_TAG,
                function_desc="MA0099.3",
            ),
        ]
        out = tmp_path / "out.tab"
        n = write_plantcare_tab(hits, out)
        assert n == 2
        lines = out.read_text().splitlines()
        assert len(lines) == 2
        for line in lines:
            parts = line.split("\t")
            assert len(parts) == 8
            assert parts[5] in {"+", "-"}
            int(parts[3])
            int(parts[4])
        first = lines[0].split("\t")
        assert first[0] == "Sobic.001G032000.v3.1"
        assert first[1] == "Dof3"
        assert first[6] == SPECIES_TAG
        assert first[7] == "MA0021.1"

    def test_creates_parent_dir(self, tmp_path: Path) -> None:
        out = tmp_path / "deep" / "nested" / "out.tab"
        write_plantcare_tab([], out)
        assert out.exists()
        assert out.read_text() == ""


class TestRunFimoMissingBinary:
    def test_raises_when_binary_missing(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError, match="not found on PATH"):
            run_fimo(
                fasta=tmp_path / "fake.fa",
                meme=tmp_path / "fake.meme",
                out_dir=tmp_path / "out",
                binary="definitely-not-a-real-fimo-binary-xyz",
            )


@pytest.mark.integration
@pytest.mark.skipif(shutil.which("fimo") is None, reason="FIMO binary not on PATH")
class TestScanEndToEnd:
    """Real FIMO invocation against the shipped JASPAR bundle.

    Skipped in CI environments without MEME suite installed.
    """

    def test_scan_writes_plantcare_tab(self, tmp_path: Path) -> None:
        repo_root = Path(__file__).resolve().parent.parent
        meme = repo_root / "example" / "10.promoter" / "JASPAR2024_plants.meme"
        fasta = repo_root / "example" / "10.promoter" / "Sb.promoter.fasta"
        if not (meme.exists() and fasta.exists()):
            pytest.skip("required fixtures missing")
        out = tmp_path / "jaspar.tab"
        n = scan(fasta=fasta, meme=meme, output=out, threshold=1e-4)
        assert n > 0
        lines = out.read_text().splitlines()
        assert len(lines) == n
        for line in lines[:20]:
            parts = line.split("\t")
            assert len(parts) == 8
            assert parts[6] == SPECIES_TAG
