"""Tests for scripts/scan_promoter_fimo.py.

Mocks FIMO output so the tests run in CI without the MEME suite. The
end-to-end ``scan()`` path that actually invokes FIMO is exercised in a
separate guarded test (skipped when the binary is missing).
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from scripts.scan_promoter_fimo import (
    FIMO_COLUMNS,
    FimoHit,
    SPECIES_TAG,
    parse_fimo_tsv,
    run_fimo,
    scan,
    write_plantcare_tab,
)

pytestmark = pytest.mark.unit


def _row(**overrides: str) -> str:
    base = {
        "motif_id": "MA0021.1",
        "motif_alt_id": "Dof3",
        "sequence_name": "Sobic.001G032000.v3.1",
        "start": "10",
        "stop": "17",
        "strand": "+",
        "score": "12.5",
        "p-value": "1e-5",
        "q-value": "1e-3",
        "matched_sequence": "ACGTACGT",
    }
    base.update(overrides)
    return "\t".join(base[col] for col in FIMO_COLUMNS) + "\n"


def _write_fimo_tsv(path: Path, rows: list[str]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = "\t".join(FIMO_COLUMNS) + "\n"
    body = header + "".join(rows) + "\n# CISML XML reference: fimo.cisml.xml\n"
    path.write_text(body)
    return path


class TestParseFimoTsv:
    def test_basic_row(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(tmp_path / "fimo.tsv", [_row()])
        hits = list(parse_fimo_tsv(tsv))
        assert len(hits) == 1
        h = hits[0]
        assert h.raw_id == "Sobic.001G032000.v3.1"
        assert h.element == "Dof3"
        assert h.sequence == "ACGTACGT"
        assert h.position == 10
        assert h.length == 8  # 17 - 10 + 1
        assert h.strand == "+"
        assert h.species == SPECIES_TAG
        assert h.function_desc == "MA0021.1"

    def test_empty_alt_id_falls_back_to_motif_id(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(
            tmp_path / "fimo.tsv",
            [_row(motif_alt_id="", motif_id="MA0042.2")],
        )
        hits = list(parse_fimo_tsv(tsv))
        assert hits[0].element == "MA0042.2"
        assert hits[0].function_desc == "MA0042.2"

    def test_strand_normalization(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(
            tmp_path / "fimo.tsv",
            [_row(strand="-"), _row(strand="+")],
        )
        strands = sorted(h.strand for h in parse_fimo_tsv(tsv))
        assert strands == ["+", "-"]

    def test_skips_blank_and_comment_lines(self, tmp_path: Path) -> None:
        path = tmp_path / "fimo.tsv"
        path.write_text(
            "\t".join(FIMO_COLUMNS) + "\n"
            "\n"
            "# generated by FIMO\n"
            + _row()
            + "\n"
            "# trailing comment\n"
        )
        assert len(list(parse_fimo_tsv(path))) == 1

    def test_drops_truncated_row(self, tmp_path: Path) -> None:
        path = tmp_path / "fimo.tsv"
        path.write_text(
            "\t".join(FIMO_COLUMNS) + "\n"
            + "MA0021.1\tDof3\tg1\n"  # too few columns
            + _row()
        )
        hits = list(parse_fimo_tsv(path))
        assert len(hits) == 1

    def test_drops_non_int_coords(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(
            tmp_path / "fimo.tsv",
            [_row(start="oops"), _row()],
        )
        hits = list(parse_fimo_tsv(tsv))
        assert len(hits) == 1

    def test_normalizes_strand_suffix_in_sequence_name(self, tmp_path: Path) -> None:
        tsv = _write_fimo_tsv(
            tmp_path / "fimo.tsv",
            [_row(sequence_name="Sobic.001G032000.v3.1(+)")],
        )
        hits = list(parse_fimo_tsv(tsv))
        # Reused _normalize_raw_id strips the strand suffix so R parses it
        assert hits[0].raw_id == "Sobic.001G032000.v3.1"


class TestWritePlantcareTab:
    def test_8_column_format(self, tmp_path: Path) -> None:
        hits = [
            FimoHit(
                raw_id="Sobic.001G032000.v3.1",
                element="Dof3",
                sequence="ACGTACGT",
                position=10,
                length=8,
                strand="+",
                species=SPECIES_TAG,
                function_desc="MA0021.1",
            ),
            FimoHit(
                raw_id="Sobic.001G032100.v3.1",
                element="MYB",
                sequence="CACGTG",
                position=42,
                length=6,
                strand="-",
                species=SPECIES_TAG,
                function_desc="MA0099.3",
            ),
        ]
        out = tmp_path / "out.tab"
        n = write_plantcare_tab(hits, out)
        assert n == 2
        lines = out.read_text().splitlines()
        assert len(lines) == 2
        for line in lines:
            parts = line.split("\t")
            assert len(parts) == 8
            assert parts[5] in {"+", "-"}
            int(parts[3])
            int(parts[4])
        first = lines[0].split("\t")
        assert first[0] == "Sobic.001G032000.v3.1"
        assert first[1] == "Dof3"
        assert first[6] == SPECIES_TAG
        assert first[7] == "MA0021.1"

    def test_creates_parent_dir(self, tmp_path: Path) -> None:
        out = tmp_path / "deep" / "nested" / "out.tab"
        write_plantcare_tab([], out)
        assert out.exists()
        assert out.read_text() == ""


class TestRunFimoMissingBinary:
    def test_raises_when_binary_missing(self, tmp_path: Path) -> None:
        with pytest.raises(FileNotFoundError, match="not found on PATH"):
            run_fimo(
                fasta=tmp_path / "fake.fa",
                meme=tmp_path / "fake.meme",
                out_dir=tmp_path / "out",
                binary="definitely-not-a-real-fimo-binary-xyz",
            )


class TestScanOrchestration:
    """Cover ``scan()``'s temp-dir and explicit work-dir branches.

    Per ``docs/development.md`` the subprocess body inside ``run_fimo`` is
    policy-exempt (don't mock the MEME binary). These tests stay above it
    by stubbing ``scan_promoter_fimo.run_fimo`` at the module level, which
    lets us exercise the orchestration (tempdir, parse, write) without
    touching ``subprocess``.
    """

    @staticmethod
    def _install_stub(monkeypatch: pytest.MonkeyPatch, rows: list[str]) -> list[dict]:
        import scripts.scan_promoter_fimo as mod

        calls: list[dict] = []

        def fake_run_fimo(
            fasta: Path,
            meme: Path,
            out_dir: Path,
            threshold: float = mod.DEFAULT_THRESHOLD,
            binary: str = mod.DEFAULT_FIMO_BINARY,
        ) -> Path:
            calls.append(
                {
                    "fasta": fasta,
                    "meme": meme,
                    "out_dir": out_dir,
                    "threshold": threshold,
                    "binary": binary,
                }
            )
            out_dir.mkdir(parents=True, exist_ok=True)
            tsv = out_dir / "fimo.tsv"
            header = "\t".join(FIMO_COLUMNS) + "\n"
            tsv.write_text(header + "".join(rows))
            return tsv

        monkeypatch.setattr(mod, "run_fimo", fake_run_fimo)
        return calls

    def test_scan_uses_tempdir_when_work_dir_none(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = self._install_stub(monkeypatch, [_row(), _row(strand="-")])
        out = tmp_path / "jaspar.tab"
        n = scan(
            fasta=tmp_path / "dummy.fa",
            meme=tmp_path / "dummy.meme",
            output=out,
        )
        assert n == 2
        lines = out.read_text().splitlines()
        assert len(lines) == 2
        assert all(len(line.split("\t")) == 8 for line in lines)
        # stub saw exactly one run; the out_dir was the ephemeral tempdir
        assert len(calls) == 1
        ephemeral = calls[0]["out_dir"]
        assert not ephemeral.exists(), "tempdir should be cleaned up after scan()"

    def test_scan_preserves_explicit_work_dir(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = self._install_stub(monkeypatch, [_row()])
        work = tmp_path / "fimo_debug"
        out = tmp_path / "jaspar.tab"
        n = scan(
            fasta=tmp_path / "dummy.fa",
            meme=tmp_path / "dummy.meme",
            output=out,
            work_dir=work,
        )
        assert n == 1
        # Debug directory is NOT cleaned up; raw fimo.tsv stays for inspection
        assert (work / "fimo.tsv").exists()
        assert calls[0]["out_dir"] == work

    def test_scan_forwards_threshold_and_binary(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        calls = self._install_stub(monkeypatch, [_row()])
        scan(
            fasta=tmp_path / "x.fa",
            meme=tmp_path / "y.meme",
            output=tmp_path / "out.tab",
            threshold=1e-6,
            binary="fimo-custom",
        )
        assert calls[0]["threshold"] == 1e-6
        assert calls[0]["binary"] == "fimo-custom"


class TestMainCli:
    """Cover ``main()``'s argparse wiring by stubbing ``scan`` itself."""

    def test_main_invokes_scan_with_parsed_args(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture
    ) -> None:
        import scripts.scan_promoter_fimo as mod

        captured: dict = {}

        def fake_scan(**kwargs) -> int:
            captured.update(kwargs)
            return 42

        monkeypatch.setattr(mod, "scan", fake_scan)

        rc = mod.main(
            [
                "--fasta", str(tmp_path / "p.fa"),
                "--meme", str(tmp_path / "m.meme"),
                "-o", str(tmp_path / "out.tab"),
                "--threshold", "1e-5",
            ]
        )
        assert rc == 0
        assert captured["fasta"] == tmp_path / "p.fa"
        assert captured["meme"] == tmp_path / "m.meme"
        assert captured["output"] == tmp_path / "out.tab"
        assert captured["threshold"] == 1e-5
        assert captured["binary"] == "fimo"
        assert captured["work_dir"] is None
        assert "wrote 42 hits" in capsys.readouterr().err

    def test_main_forwards_keep_fimo_dir_as_work_dir(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        import scripts.scan_promoter_fimo as mod

        captured: dict = {}
        monkeypatch.setattr(
            mod, "scan", lambda **kw: (captured.update(kw) or 0)
        )
        rc = mod.main(
            [
                "--fasta", str(tmp_path / "p.fa"),
                "--meme", str(tmp_path / "m.meme"),
                "-o", str(tmp_path / "out.tab"),
                "--keep-fimo-dir", str(tmp_path / "debug"),
                "--fimo-binary", "/opt/fimo",
            ]
        )
        assert rc == 0
        assert captured["work_dir"] == tmp_path / "debug"
        assert captured["binary"] == "/opt/fimo"


class TestModuleEntrypoint:
    def test_help_runs_via_dash_m(self, tmp_path: Path) -> None:
        """``python -m scripts.scan_promoter_fimo --help`` exercises the
        ``raise SystemExit(main())`` tail without invoking the real FIMO
        binary — argparse short-circuits with ``SystemExit(0)``."""
        import runpy
        import sys

        original = sys.argv
        sys.argv = ["scan_promoter_fimo.py", "--help"]
        try:
            with pytest.raises(SystemExit) as exc:
                runpy.run_module(
                    "scripts.scan_promoter_fimo", run_name="__main__"
                )
            assert exc.value.code == 0
        finally:
            sys.argv = original


@pytest.mark.integration
@pytest.mark.skipif(shutil.which("fimo") is None, reason="FIMO binary not on PATH")
class TestScanEndToEnd:
    """Real FIMO invocation against the shipped JASPAR bundle.

    Skipped in CI environments without MEME suite installed.
    """

    def test_scan_writes_plantcare_tab(self, tmp_path: Path) -> None:
        repo_root = Path(__file__).resolve().parent.parent
        meme = repo_root / "example" / "10.promoter" / "JASPAR2024_plants.meme"
        fasta = repo_root / "example" / "10.promoter" / "Sb.promoter.fasta"
        if not (meme.exists() and fasta.exists()):
            pytest.skip("required fixtures missing")
        out = tmp_path / "jaspar.tab"
        n = scan(fasta=fasta, meme=meme, output=out, threshold=1e-4)
        assert n > 0
        lines = out.read_text().splitlines()
        assert len(lines) == n
        for line in lines[:20]:
            parts = line.split("\t")
            assert len(parts) == 8
            assert parts[6] == SPECIES_TAG
